import type { Episode, VisualContinuity } from './types';

export function ShotContinuity({ episode, value, onChange, disabled }: { episode: Episode; value: VisualContinuity | null; onChange: (value: VisualContinuity) => void; disabled: boolean }) {
  const bible = episode.bible as { characters?: { id: string }[]; props?: { id: string }[] } | null;
  const ids = bible?.characters?.map(character => character.id) ?? [];
  const roles = [...ids.map(id => `character:${id}`), ...(bible?.props ?? []).map(prop => `prop:${prop.id}`), 'environment', 'style'];
  const labels: Record<string, string> = { environment: '场景参考（无人或道具镜头）', style: '风格参考' };
  function update(change: Partial<VisualContinuity>) { if (value) onChange({ ...value, ...change }); }
  return <details className="preview-extra"><summary>出场角色、参考素材与连续状态</summary>
    {!value ? <><p>旧镜头尚未声明连续状态。多角色时需要明确选择本镜参考。</p><button type="button" disabled={disabled} onClick={() => onChange({ scene_id: 'scene_1', visible_character_ids: [], reference_roles: ['environment'], framing: 'medium', state_in: {}, state_out: {}, intentional_jump: '' })}>补充镜头约束</button></> : <>
      <div className="fields two"><label className="field">场景编号<input value={value.scene_id} disabled={disabled} onChange={event => update({ scene_id: event.target.value })} /></label><label className="field">景别<select disabled={disabled} value={value.framing} onChange={event => update({ framing: event.target.value as VisualContinuity['framing'] })}><option value="wide">全景</option><option value="medium">中景</option><option value="close_up">近景</option><option value="insert">道具插入特写</option></select></label></div>
      <p>出场角色（无人或仅道具可不选）</p><div className="actions">{ids.map(id => <label className="check" key={id}><input type="checkbox" disabled={disabled} checked={value.visible_character_ids.includes(id)} onChange={event => update({ visible_character_ids: event.target.checked ? [...value.visible_character_ids, id] : value.visible_character_ids.filter(item => item !== id), reference_roles: event.target.checked ? value.reference_roles : (value.reference_roles.filter(role => role !== `character:${id}`).length ? value.reference_roles.filter(role => role !== `character:${id}`) : ['environment']) })} />{id}</label>)}</div>
      <label className="field">主要参考素材<select disabled={disabled} value={value.reference_roles[0]} onChange={event => update({ reference_roles: [event.target.value, ...value.reference_roles.filter(role => role !== event.target.value)] })}>{roles.map(role => <option key={role} value={role}>{labels[role] ?? role.replace(/^(character|prop):/, '')}</option>)}</select></label>
      <p>辅助参考（仅在工作流支持时使用）</p><div className="actions">{roles.filter(role => role !== value.reference_roles[0] && (!role.startsWith('character:') || value.visible_character_ids.includes(role.replace(/^(character|prop):/, '')))).map(role => <label className="check" key={role}><input type="checkbox" disabled={disabled} checked={value.reference_roles.includes(role)} onChange={event => update({ reference_roles: event.target.checked ? [...value.reference_roles, role] : value.reference_roles.filter(item => item !== role) })} />{labels[role] ?? role.replace(/^(character|prop):/, '')}</label>)}</div>
      <small className="muted">单参考工作流使用第一项。其余参考：{value.reference_roles.slice(1).map(role => labels[role] ?? role.replace(/^(character|prop):/, '')).join('、') || '无'}。修改主参考时，请同时核对出场角色和提示词。</small>
      {(['state_in', 'state_out'] as const).map(field => <div className="field" key={field}><strong>{field === 'state_in' ? '入镜状态' : '出镜状态'}</strong>{Object.entries(value[field]).map(([key, state], index) => <div className="fields two" key={index}><input aria-label={`${field === 'state_in' ? '入镜' : '出镜'}状态属性 ${index + 1}`} disabled={disabled} value={key} placeholder="对象属性，例如 pen.holder" onChange={event => { const entries = Object.entries(value[field]); entries[index] = [event.target.value, state]; update({ [field]: Object.fromEntries(entries) }); }} /><input aria-label={`${field === 'state_in' ? '入镜' : '出镜'}状态值 ${index + 1}`} disabled={disabled} value={state} placeholder="状态，例如 desk" onChange={event => update({ [field]: { ...value[field], [key]: event.target.value } })} /></div>)}<button type="button" disabled={disabled || '' in value[field]} onClick={() => update({ [field]: { ...value[field], '': '' } })}>添加状态</button></div>)}
      <small className="muted">同场景使用相同属性名和值，状态改变应由镜内动作完成。反打时，暂时离开画面的物品也保留已知状态。</small>
      <label className="field">有意跳转的原因（通常留空）<input disabled={disabled} value={value.intentional_jump} onChange={event => update({ intentional_jump: event.target.value })} /></label>
    </>}
  </details>;
}
